### PR TITLE
[fix] collection of fixes after AP/FBW merge

### LINKED ISSUE #2840: Tests failing
The current tests on master are failing because of some includes introduced with #2828 :
```
In file included from modules/core/settings.c:29:0:
/home/pprz/paparazzi/var/aircrafts/Minimag/sim/generated/settings.h:18:10: fatal error: modules/intermcu/inter_mcu.h: No such file or directory
 #include "modules/intermcu/inter_mcu.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Next to that also some extra warnings were introduced in NPS which could be easily resolved. @gautierhattenberger can you take a look at it?

### PR DESCRIPTION
**Pull request by gautierhattenberger**
some errors after #2828
- fix all airframes using dual boards
- fix calls to ap_state or old imcu API
- fix some includes
- protect some code to compile test programs (without 'commands' API)

close #2840

### CODE REVIEW

**Review by fvantienen — APPROVED** [review]
Looks good!
