### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by fvantienen** [paparazzi/paparazzi#2840]
The current tests on master are failing because of some includes introduced with #2828 :
```
In file included from modules/core/settings.c:29:0:
/home/pprz/paparazzi/var/aircrafts/Minimag/sim/generated/settings.h:18:10: fatal error: modules/intermcu/inter_mcu.h: No such file or directory
 #include "modules/intermcu/inter_mcu.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Next to that also some extra warnings were introduced in NPS which could be easily resolved. @gautierhattenberger can you take a look at it?

**Comment by gautierhattenberger** [comment]
I'm already on it
